'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { FileText, Download, ArrowLeft, Loader2, Sprout, MapPin, Activity, Droplets } from 'lucide-react';
import Link from 'next/link';

interface ReportData {
  id: string;
  title: string;
  type: string;
  date: string;
  metadata?: {
    crop: string;
    lat: number;
    lng: number;
    ndvi: number;
  };
}

export default function ReportViewPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const router = useRouter();
  const [report, setReport] = useState<ReportData | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function fetchReport() {
      if (!params.id) return;
      
      const { data, error } = await supabase
        .from('reports')
        .select('*')
        .eq('id', params.id as string)
        .single();
        
      if (data) {
        setReport(data);
      }
      setIsLoading(false);
      
      // Auto-trigger print if requested via query param
      if (searchParams.get('print') === 'true' && data) {
        setTimeout(() => {
          window.print();
        }, 500); // Small delay to ensure render
      }
    }
    fetchReport();
  }, [params.id, searchParams]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-paper-ivory flex justify-center items-center">
        <Loader2 className="w-8 h-8 animate-spin text-moss" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-paper-ivory flex flex-col justify-center items-center">
        <h2 className="text-2xl font-serif text-deep-forest mb-4">Report Not Found</h2>
        <button onClick={() => router.back()} className="text-moss hover:underline">Return to Reports</button>
      </div>
    );
  }

  const getNdviAssessment = (ndvi: number) => {
    if (ndvi > 0.7) return "Vegetation is highly dense and healthy. Photosynthetic activity is optimal. Standard irrigation and monitoring are recommended.";
    if (ndvi > 0.4) return "Vegetation shows moderate health. Some stress factors may be present. Consider checking soil moisture and nutrient levels.";
    return "Vegetation is sparse or under significant stress. Immediate intervention, such as targeted watering or fertilization, is strongly advised.";
  };

  return (
    <div className="min-h-screen bg-white md:bg-paper-ivory font-sans selection:bg-moss/30 selection:text-deep-forest">
      {/* Non-printable Header & Controls */}
      <div className="print:hidden bg-white border-b border-soft-line px-6 py-4 flex justify-between items-center sticky top-0 z-50 shadow-sm">
        <button 
          onClick={() => router.back()}
          className="flex items-center gap-2 text-ink/60 hover:text-ink transition-colors text-sm font-medium"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Reports
        </button>
        <button 
          onClick={() => window.print()}
          className="bg-deep-forest text-white px-5 py-2 rounded-full text-sm font-medium hover:bg-moss transition-colors flex items-center gap-2 shadow-sm"
        >
          <Download className="w-4 h-4" /> Download PDF
        </button>
      </div>

      {/* Printable Report Document */}
      <main className="max-w-4xl mx-auto md:my-12 bg-white md:border border-soft-line md:shadow-lg print:border-none print:shadow-none print:m-0 print:p-0 p-8 md:p-16">
        
        {/* Document Header */}
        <header className="flex justify-between items-start border-b-2 border-deep-forest/20 pb-8 mb-8">
          <div className="flex items-center gap-3">
            <Sprout className="w-10 h-10 text-deep-forest" />
            <div>
              <h1 className="font-serif text-3xl tracking-tight text-ink font-medium">AgriSetu</h1>
              <div className="text-xs font-medium uppercase tracking-widest text-ink/50 mt-1">Agricultural Intelligence</div>
            </div>
          </div>
          <div className="text-right">
            <div className="text-sm font-medium text-ink/60">{report.type}</div>
            <div className="text-lg font-serif text-deep-forest mt-1">{report.date}</div>
            <div className="text-xs text-ink/40 mt-1">ID: {report.id.split('-')[0]}</div>
          </div>
        </header>

        {/* Report Title */}
        <div className="mb-12">
          <h2 className="text-4xl font-serif text-deep-forest font-medium tracking-tight mb-3">{report.title}</h2>
          <p className="text-ink/60 leading-relaxed max-w-2xl">This document contains an automated analysis generated by AgriSetu's satellite monitoring systems, summarizing field health, location data, and actionable agronomic insights.</p>
        </div>

        {/* Data Grid */}
        {report.metadata ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
            
            {/* Field Identity */}
            <div className="bg-paper-ivory p-6 rounded-xl border border-soft-line">
              <div className="flex items-center gap-2 text-moss mb-4">
                <MapPin className="w-5 h-5" />
                <h3 className="font-medium">Location & Crop</h3>
              </div>
              <div className="space-y-3">
                <div>
                  <div className="text-xs text-ink/50 uppercase tracking-widest font-medium">Primary Crop</div>
                  <div className="text-lg text-ink font-medium capitalize">{report.metadata.crop}</div>
                </div>
                <div>
                  <div className="text-xs text-ink/50 uppercase tracking-widest font-medium">Coordinates</div>
                  <div className="text-lg text-ink font-medium font-mono text-sm">{report.metadata.lat.toFixed(6)}, {report.metadata.lng.toFixed(6)}</div>
                </div>
              </div>
            </div>

            {/* Health Metrics */}
            <div className="bg-paper-ivory p-6 rounded-xl border border-soft-line">
              <div className="flex items-center gap-2 text-moss mb-4">
                <Activity className="w-5 h-5" />
                <h3 className="font-medium">Health Metrics</h3>
              </div>
              <div className="space-y-3">
                <div>
                  <div className="text-xs text-ink/50 uppercase tracking-widest font-medium">Current NDVI Score</div>
                  <div className="flex items-end gap-2">
                    <div className="text-3xl text-deep-forest font-medium">{report.metadata.ndvi.toFixed(2)}</div>
                    <div className="text-sm text-ink/60 mb-1">/ 1.00</div>
                  </div>
                </div>
                {/* Visual Indicator Bar */}
                <div className="w-full h-2 bg-soft-line rounded-full overflow-hidden mt-2">
                  <div 
                    className={`h-full ${report.metadata.ndvi > 0.7 ? 'bg-moss' : report.metadata.ndvi > 0.4 ? 'bg-yellow-500' : 'bg-terracotta'}`}
                    style={{ width: `${Math.max(0, Math.min(100, report.metadata.ndvi * 100))}%` }}
                  />
                </div>
              </div>
            </div>
            
          </div>
        ) : (
          <div className="bg-paper-ivory p-6 rounded-xl border border-soft-line text-ink/50 italic mb-12">
            No detailed telemetry data is available for this report.
          </div>
        )}

        {/* AI Insights Section */}
        {report.metadata && (
          <div className="mb-12">
            <h3 className="text-2xl font-serif text-deep-forest font-medium mb-6 flex items-center gap-3">
              <Droplets className="w-6 h-6 text-moss" /> Analysis & Recommendations
            </h3>
            <div className="prose prose-stone max-w-none">
              <p className="text-ink leading-relaxed">
                Based on the multi-spectral satellite imagery captured and processed for the coordinates <strong>{report.metadata.lat.toFixed(4)}, {report.metadata.lng.toFixed(4)}</strong>, the following agronomic assessment has been generated for your <strong>{report.metadata.crop}</strong> crop.
              </p>
              
              <div className="bg-moss/5 border-l-4 border-moss p-6 my-6 rounded-r-xl">
                <h4 className="text-lg font-medium text-deep-forest mb-2">NDVI Assessment ({report.metadata.ndvi.toFixed(2)})</h4>
                <p className="text-ink/80 leading-relaxed m-0">
                  {getNdviAssessment(report.metadata.ndvi)}
                </p>
              </div>
              
              <p className="text-ink leading-relaxed">
                Continual monitoring is advised. Weather fluctuations in the upcoming week may require adjustments to your irrigation schedule. Please check the AgriSetu dashboard for real-time temporal progression and climate alerts.
              </p>
            </div>
          </div>
        )}

        {/* Document Footer */}
        <footer className="mt-16 pt-8 border-t border-soft-line text-center text-xs text-ink/40">
          <p>Generated by AgriSetu Intelligence on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}</p>
          <p className="mt-1">This report is for informational purposes only. Consult local agronomists for major interventions.</p>
        </footer>

      </main>
    </div>
  );
}
