import React from 'react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-paper-ivory font-sans selection:bg-moss/30 selection:text-deep-forest text-ink pb-24">
      <div className="bg-deep-forest text-white py-16 px-6 text-center border-b border-moss">
        <h1 className="text-4xl font-serif font-medium tracking-tight mb-4">Terms and Conditions</h1>
        <p className="text-sand/80 max-w-2xl mx-auto">Please read these terms and conditions carefully before using the AgriSetu platform.</p>
      </div>
      
      <div className="max-w-3xl mx-auto mt-12 px-6">
        <div className="bg-white p-8 md:p-12 rounded-2xl border border-soft-line shadow-sm prose prose-stone max-w-none">
          <p className="text-sm text-ink/60 mb-8 font-medium tracking-wide uppercase">Last updated: September 2026</p>
          
          <h2 className="text-2xl font-serif text-deep-forest mb-4">1. Acceptance of Terms</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            By accessing, browsing, or using the AgriSetu platform, website, and related mobile applications (collectively, "the Platform"), you acknowledge that you have read, understood, and agree to be bound by these comprehensive Terms and Conditions. If you do not agree with any part of these terms, you must discontinue your use of our services immediately.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">2. Description of Service and Limitations</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            AgriSetu provides advanced agricultural intelligence, satellite monitoring, field reporting tools, and artificial intelligence diagnostics. <strong>Important Disclaimer:</strong> The data provided—including but not limited to Normalized Difference Vegetation Index (NDVI) assessments, hyperspectral analysis, weather forecasts, pest risk models, and generative AI disease diagnoses—are algorithmically generated estimates based on available remote sensing data and third-party APIs. 
            <br/><br/>
            These insights are intended for informational and planning purposes only and <strong>do not constitute, nor should they replace, professional agronomic consultation.</strong> Actual field conditions may vary significantly from satellite representations due to cloud cover, atmospheric interference, and model latency.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">3. Artificial Intelligence and Machine Learning</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            Certain features of the Platform, such as the Image Diagnostic tool, utilize generative Artificial Intelligence (AI) and Machine Learning (ML) models. By using these features, you acknowledge that AI models can occasionally produce inaccurate, misleading, or "hallucinated" outputs. You agree that AgriSetu is not responsible for misdiagnoses of crop diseases or incorrect treatment recommendations generated by the AI, and you should always verify treatments with a certified agricultural expert before applying any chemicals, fertilizers, or pesticides.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">4. Data Privacy, Security, and User-Generated Content</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            We prioritize the security of your agricultural data. Your field boundaries (GeoJSON data), reports, uploaded images, and personal information are stored securely. By uploading data to the Platform, you grant AgriSetu a non-exclusive, worldwide, royalty-free license to use, store, compute, and process this data to provide our services to you, and to anonymize and aggregate this data to improve our machine learning models. We will never sell your personally identifiable information to third parties without explicit consent.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">5. Acceptable Use Policy</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            You agree to use the Platform only for lawful purposes. You are strictly prohibited from:
          </p>
          <ul className="list-disc pl-6 mb-6 text-ink/90 space-y-2">
            <li>Reverse-engineering, decompiling, or disassembling any part of the Platform or its proprietary AI/ML algorithms.</li>
            <li>Using automated scripts, spiders, or scrapers to extract satellite imagery, weather data, or diagnostic reports.</li>
            <li>Uploading images or data that contain malicious code, viruses, or illegal content.</li>
            <li>Attempting to gain unauthorized access to other users' field data or accounts.</li>
          </ul>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">6. Intellectual Property Rights</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            All original content, features, functionality, UI design, logos, and software code on the Platform are the exclusive property of AgriSetu and its licensors, protected by international copyright, trademark, and intellectual property laws. You retain full ownership of the raw data you upload, but the processed reports, NDVI visualizations, and AI insights generated by the Platform remain the intellectual property of AgriSetu.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">7. Limitation of Liability and Indemnification</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            To the maximum extent permitted by applicable law, AgriSetu and its affiliates, directors, employees, and agents shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to <strong>loss of crop yield, loss of profits, soil degradation, or financial ruin</strong> resulting from the use or inability to use our services, or from reliance on the data provided by the Platform. You agree to indemnify and hold harmless AgriSetu from any claims arising out of your agricultural operations or violation of these Terms.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">8. Governing Law and Dispute Resolution</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            These Terms shall be governed by and construed in accordance with the laws of India, specifically focusing on data protection guidelines and agricultural technology regulations. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in New Delhi, India.
          </p>

          <h2 className="text-2xl font-serif text-deep-forest mb-4">9. Modifications to Terms</h2>
          <p className="mb-6 leading-relaxed text-ink/90">
            AgriSetu reserves the right to modify or replace these Terms at any time. We will provide reasonable notice of any material changes via email or an in-platform notification. Your continued use of the Platform after such modifications constitutes your acceptance of the new Terms.
          </p>

          <div className="mt-12 p-6 bg-sand/30 rounded-xl border border-sand">
            <h3 className="text-xl font-serif text-deep-forest mb-2">Contact Us</h3>
            <p className="text-ink/80 text-sm">
              If you have any questions about these Terms and Conditions, please contact our legal team at: <br/>
              <strong>legal@agrisetu.in</strong>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
